name: Latest blog post workflow
on:
  schedule:
    # Runs at minute 0 past hour 0, 6, 12, and 18
    - cron: '0 0,6,12,18 * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://medium.com/feed/@evrentan'
